"""Explicit fourth-family Task client; status-first bounded same-report recovery."""
from __future__ import annotations

from .access_quota import AccessQuotaPolicy, AccessQuotaError

import os
from pathlib import Path
import time
from typing import Any, Optional

from . import paid_service_trial_contract as c
from .paid_service_trial_models import (
    PaidServiceTrialTask, PaidServiceTrialTaskPage, PaidServiceTrialClaim, model_for, parse_claim,
    PaidServiceTrialAbandonment, PaidServiceTrialCompletionReceipt,
    PaidServiceTrialSubmissionStatus, FrozenPaidServiceTrialReport,
)
from .paid_service_trial_transport import (
    PaidServiceTrialTransport, PaidServiceTrialError, PaidServiceTrialAPIError,
    PaidServiceTrialTransportError, _public_boundary,
)


class PaidServiceTrialTaskClient:
    def __init__(self, *, version: str='v2', transport: Any=None, monotonic: Any=time.monotonic, claim_directory: Any=None, access_quota: Optional[AccessQuotaPolicy]=None) -> None:
        self.version=c.validate_version(version)
        self._transport=transport or PaidServiceTrialTransport(version=version, access_quota=access_quota)
        if isinstance(self._transport, PaidServiceTrialTransport) and self._transport.version!=version:
            raise ValueError('Incompatible Paid Service Trial transport version.')
        self._monotonic=monotonic
        if claim_directory is None:
            if os.name=='nt':
                local=os.environ.get('LOCALAPPDATA')
                if not local:raise ValueError('Private Claim directory required.')
                claim_directory=Path(local)/'ln-church-agent'/'claims'
            else:
                claim_directory=Path.home()/'.ln-church-agent'/'claims'
        self.claim_directory=Path(claim_directory)

    def __enter__(self) -> Any:
        return self

    def close(self) -> None:
        self._transport.close()

    def __exit__(self,*args: Any) -> None:
        self.close()

    def _definition(self, value: Any) -> Any:
        bundle=c.load_contract_bundle(c.version_of(value))
        if value.task_definition_digest!=bundle['manifest']['task_definition_digest']:
            raise ValueError('Invalid Paid Service Trial Definition binding.')
        return value

    @_public_boundary
    def list_tasks(self,limit: int=25,cursor: Any=None) -> PaidServiceTrialTaskPage:
        c.positive_bound(limit,'limit',integer=True,maximum=50)
        page=model_for('page',self.version).model_validate(self._transport.list_tasks(limit=limit,cursor=cursor))
        if len(page.tasks)>limit:
            raise ValueError
        for task in page.tasks:self._definition(task)
        return page

    @_public_boundary
    def get_task(self,task_id: str) -> PaidServiceTrialTask:
        task=model_for('task',self.version).model_validate(self._transport.get_task(c.validate_task_id(task_id)))
        if task.task_id!=task_id:
            raise ValueError
        return self._definition(task)

    @_public_boundary
    def claim_task(self,task_id: str,agent_id: str,reward_address: str,*,idempotency_key: str) -> PaidServiceTrialClaim:
        c.validate_task_id(task_id);c.validate_opaque_id(idempotency_key,'idempotency_key')
        body=c.canonical_bytes(dict(schema_version='ln_church.agent_task_claim_request.v1',
                                    agent_id=c.validate_agent_id(agent_id),reward_address=c.address(reward_address)))
        return self._claim_request(task_id,idempotency_key,body)

    @_public_boundary
    def recover_claim(self,task_id: str,*,idempotency_key: str) -> PaidServiceTrialClaim:
        """One explicit same-request retry, or return its durable credential.

        Reuse this client's private directory after restarting. No new key,
        request, Claim deadline or payment is generated by recovery.
        """
        return self._claim_request(task_id,idempotency_key,None)

    def _claim_request(self,task_id: str,key: str,body: Any) -> PaidServiceTrialClaim:
        from .paid_service_trial_journal import _ClaimRequest, PaidServiceTrialJournal
        record=_ClaimRequest(self.claim_directory,self.version,task_id,key)
        with record.guard():
            saved=record.read(body)
            if saved['state']=='REJECTED':
                error=saved['rejection']
                raise PaidServiceTrialAPIError(error['code'],status_code=error['status'],
                    reason=error.get('reason'),request_id=error.get('request_id'))
            if saved['state']=='READY':
                original=parse_claim(saved['claim'])
                claim=PaidServiceTrialJournal.load_claim(self.claim_directory,task_id,original.execution_id)
                if claim._private_payload()!=original._private_payload():
                    raise ValueError('Invalid Claim binding.')
                return self._definition(claim)
            if saved['claim'] is None:
                prior=saved['state']
                saved['state']='UNKNOWN';record.save(saved)
                try:
                    call = self._transport.claim_task
                    if (prior == 'UNKNOWN' and hasattr(self._transport, 'recover_claim')
                            and not self._transport.access_quota.has_operation(
                                'POST', c.PUBLIC_API_ORIGIN+c.task_claim_path(task_id),
                                {'Content-Type':'application/json','Idempotency-Key':key},
                                saved['body'].encode('utf-8'))):
                        call = self._transport.recover_claim
                    raw=call(task_id,saved['body'].encode('utf-8'),idempotency_key=key)
                except AccessQuotaError as error:
                    if error.origin_not_sent:
                        saved['state']='NOT_SENT';record.save(saved)
                    raise
                except PaidServiceTrialAPIError as error:
                    if 400<=error.status_code<500 and error.public_error_code!='invalid_response':
                        saved.update(state='REJECTED',rejection=dict(code=error.public_error_code,status=error.status_code,
                            reason=error.reason,request_id=error.request_id))
                        record.save(saved)
                        raise
                    raise PaidServiceTrialTransportError('CLAIM_OUTCOME_UNKNOWN',request_bytes_sent=True,
                        status_code=error.status_code,public_error_code=error.public_error_code,
                        reason=error.reason,request_id=error.request_id) from None
                except PaidServiceTrialError as error:
                    if error.request_bytes_sent is False and prior=='NOT_SENT':
                        saved['state']='NOT_SENT';record.save(saved)
                        raise
                    raise PaidServiceTrialTransportError('CLAIM_OUTCOME_UNKNOWN',request_bytes_sent=error.request_bytes_sent,
                        status_code=error.status_code,public_error_code=error.public_error_code,
                        reason=error.reason,request_id=error.request_id) from None
                except Exception:
                    raise PaidServiceTrialTransportError('CLAIM_OUTCOME_UNKNOWN') from None
                try:
                    claim=model_for('claim',self.version).model_validate(raw)
                    request=c.decode_json_object(saved['body'].encode(),65536)
                    if claim.task_id!=task_id or claim.reward_address!=request['reward_address']:
                        raise ValueError
                    self._definition(claim)
                except Exception:
                    raise PaidServiceTrialTransportError('CLAIM_OUTCOME_UNKNOWN',request_bytes_sent=True,
                        status_code=getattr(raw,'_http_status',None)) from None
                saved.update(state='RECEIVED',claim=claim._private_payload());record.save(saved)
            claim=self._definition(parse_claim(saved['claim']))
            # Do not return a usable credential until both private credential
            # and the existing immutable purchase journal are durable.
            PaidServiceTrialJournal(self.claim_directory,claim)
            saved['state']='READY';record.save(saved)
            return claim

    @_public_boundary
    def abandon_claim(self,claim: PaidServiceTrialClaim,*,idempotency_key: str) -> PaidServiceTrialAbandonment:
        claim=parse_claim(claim)
        body=c.canonical_bytes(dict(schema_version='ln_church.agent_task_abandon_request.paid_service_trial.'+c.version_of(claim),execution_id=claim.execution_id))
        result=model_for('abandon',c.version_of(claim)).model_validate(self._transport.abandon_claim(
            claim.task_id,claim._claim_token_value(),body,idempotency_key=c.validate_opaque_id(idempotency_key,'idempotency_key'),version=c.version_of(claim)))
        if result.task_id!=claim.task_id or result.execution_id!=claim.execution_id:
            raise ValueError
        return result

    @_public_boundary
    def get_submission_status(self,claim: PaidServiceTrialClaim,frozen_report: FrozenPaidServiceTrialReport,*,timeout_seconds: float=20.0) -> PaidServiceTrialSubmissionStatus:
        claim=parse_claim(claim);frozen_report.model.require_claim(claim)
        result=model_for('status',c.version_of(claim)).model_validate(self._transport.get_submission_status(
            claim.task_id,frozen_report.submission_id,claim._claim_token_value(),timeout_seconds=timeout_seconds,version=c.version_of(claim)))
        result.require_report(claim,frozen_report)
        return result

    def complete_task(self,claim: PaidServiceTrialClaim,frozen_report: FrozenPaidServiceTrialReport,*,journal: Any) -> Any:
        return self._complete(claim,frozen_report,journal=journal,explicit=False,supplement=False)

    def recover_completion(self,claim: PaidServiceTrialClaim,frozen_report: FrozenPaidServiceTrialReport,*,journal: Any) -> Any:
        return self._complete(claim,frozen_report,journal=journal,explicit=True,supplement=False)

    def supplement_transaction(self,claim: PaidServiceTrialClaim,frozen_report: FrozenPaidServiceTrialReport,transaction_hash: str,*,journal: Any) -> Any:
        return self._complete(claim,frozen_report.supplement(transaction_hash),journal=journal,explicit=True,supplement=True)

    @_public_boundary
    def _complete(self,claim: PaidServiceTrialClaim,report: FrozenPaidServiceTrialReport,*,journal: Any,explicit: bool,supplement: bool) -> Any:
        claim=parse_claim(claim)
        journal.require_binding(claim);journal.require_report(report)
        deadline=self._monotonic()+90.0
        with journal.operation_guard():
            data=journal.require_report(report)
            if data['rejection'] is not None and not explicit:
                raise PaidServiceTrialTransportError('REPORT_INVALID')
            # The original receipt/result survives expiry and never needs a
            # new Submission. Explicit recovery still makes one saved read.
            if data['result'] is not None and not explicit:
                return journal._result_model(data['result'])
            needs_status=explicit or data['completion_attempts']>0
            posts=0
            while self._monotonic()<deadline:
                data=journal.snapshot()
                if needs_status:
                    try:
                        status=self.get_submission_status(claim,report,timeout_seconds=min(20.0,deadline-self._monotonic()))
                        # Status validates the immutable core, but it does not
                        # acknowledge a new locator; retain the prior locator.
                        journal.save_result(status,journal.load_report())
                        if not supplement or status.evaluation.state!='PENDING':return status
                    except PaidServiceTrialAPIError as error:
                        if error.public_error_code!='not_found':raise
                    except PaidServiceTrialError:
                        raise PaidServiceTrialTransportError('COMPLETION_OUTCOME_UNKNOWN')
                if data['rejection'] is not None:
                    raise PaidServiceTrialTransportError('REPORT_INVALID')
                if explicit:
                    if posts>=1:break
                elif data['completion_attempts']>=3:break
                remaining=deadline-self._monotonic()
                if remaining<=0:break
                # Reserve before I/O: a crash consumes this client attempt.
                journal.reserve_report(report,explicit=explicit and data['completion_attempts']>=3)
                key=report.submission_id
                if report.model.transaction_hash:
                    key='tx_'+c.digest([report.submission_id,report.model.transaction_hash])
                try:
                    raw=self._transport.post_completion_bytes(claim.task_id,claim._claim_token_value(),
                            report.submission_id,report.to_bytes(),idempotency_key=key,timeout_seconds=min(20.0,remaining),version=c.version_of(claim))
                    result=model_for('receipt',c.version_of(claim)).model_validate(raw)
                    result.require_report(claim,report);journal.save_result(result,report)
                    return result
                except PaidServiceTrialAPIError as error:
                    if error.public_error_code in {'report_conflict','idempotency_conflict','report_binding_invalid','claim_expired','claim_not_active','report_already_accepted'}:
                        journal.save_rejection(error.public_error_code)
                        raise
                    if error.status_code!=503:raise
                except PaidServiceTrialError:
                    pass
                posts+=1;needs_status=True
            raise PaidServiceTrialTransportError('COMPLETION_OUTCOME_UNKNOWN')
